# Generated by Django 5.2.14 on 2026-05-12 02:48

import apps.classification.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='AudioFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=apps.classification.models.user_audio_upload_to)),
                ('original_filename', models.CharField(max_length=255)),
                ('duration_seconds', models.FloatField(default=0)),
                ('sample_rate', models.IntegerField(blank=True, null=True)),
                ('size_bytes', models.BigIntegerField(default=0)),
                ('extra_metadata', models.JSONField(blank=True, default=dict)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audio_files', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-uploaded_at',),
            },
        ),
        migrations.CreateModel(
            name='ClassificationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confidence', models.FloatField()),
                ('probabilities', models.JSONField(default=dict)),
                ('num_chunks', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('audio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='classification.audiofile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classification_results', to=settings.AUTH_USER_MODEL)),
                ('predicted_genre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='predictions', to='classification.genre')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
